### PR TITLE
make added scripts go to the left side of the backpack

### PR DESCRIPTION
**Pull request by joker314**
Untested but it should work.

### CODE REVIEW

**Comment by tjvr** [comment]
Hi! [llk/s2forums](https://github.com/llk/s2forums) is the best place for this. :)

**Comment by joker314** [comment]
HI @tjvr , I'm so sorry but I couldn't find the `backpack.js` file there. Do you mind linking to it?

**Comment by joker314** [comment]
Just wondering

**Comment by tjvr** [comment]
Search for it?

**Comment by joker314** [comment]
[I did](https://github.com/LLK/s2forums/search?q=backpack.js&type=Code&utf8=%E2%9C%93), I'm sorry but I searched but I couldn't find it please could you link to it? Sorry to bother you. Also, is it OK for it to be merged here too?

**Comment by tjvr** [comment]
https://github.com/blog/793-introducing-the-file-finder

No, this repo is unused.

**Pull request closed without merging**
